### ISSUE TITLE
[feat] mysql 컨테이너에 볼륨 설정하여 컨테이너가 다운되도 데이터가 유지되도록 개선

### ISSUE THREAD

**Issue by yonghwankim-dev** [masters2023-project-03-second-hand/apple-market#145]
## 구현해야 할것

- mysql 컨테이너에 볼륨 설정하여 컨테이너가 다운되도 데이터가 유지되도록 개선

## 구현방법
docker-compose.yml 파일에 volume 설정
```
version: "3.8"
services:
...
  db:
    container_name: second_hand_db
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - second_hand-data:/var/lib/mysql
    command:
      - --local-infile=1
    networks:
      - backend_net
...
volumes:
  second_hand-data:
```
- second_hand-data 볼륨 설정

## troubleshooting
application.yml 파일에서 dev 프로파일 설정중 ddl-auto를 create로 설정하여 볼륨을 설정하였음에도 테이블이 초기화되는 문제가 있었습니다.
```
ddl-auto: none
```
위와 같이 변경하여 해결하였습니다.
